package errormessage

const (
	SUCCESS= 200
	ERROR = 500
	ERROR_DATA_NOEXIST =50000
	//CODE =1000 用户模块的错误
	ERROR_USERNAME_USE =1001
	ERROR_PASSWORD_WRONG=1002
	ERROR_USER_NOTEXIST=1003
	ERROR_TOKEN_EXISTS=1004
	ERROR_TOKEN_RUNTIME=1005
	ERROR_TOKEN_WRONG=1006
	ERROR_TOKEN_TYPR_ERONG=1007
	//2000开头的错误 文章模块的错误
	//3000开头的错误  分类模块的错误
	ERROR_CATRNAME_USERD= 30001
	ERROR_ART_NOTEXIST=2001
)


var codemsg=map[int]string{
	SUCCESS :"OK",
	ERROR:"FALSE",
	ERROR_USERNAME_USE :"用户名已经存在！",
	ERROR_PASSWORD_WRONG :"密码错误",
	ERROR_USER_NOTEXIST :"用户不存在",
	ERROR_TOKEN_EXISTS :"token不存在",
	ERROR_TOKEN_RUNTIME: "token 超时了",
	ERROR_TOKEN_WRONG : "token错误",
	ERROR_TOKEN_TYPR_ERONG: "token格式错误",
	ERROR_DATA_NOEXIST:"数据库中数据不存在",
	ERROR_CATRNAME_USERD :"分类已经存在",
	ERROR_ART_NOTEXIST:"文章不存在",
}

func GetErrorMessage(code int )string{
	return  codemsg[code]
}